import fs from "node:fs";
import { DEMO_DB_BASE64 } from "@/lib/demo-db-data";

/**
 * Single source of truth for "is this instance a public demo deploy?".
 * Exposed via NEXT_PUBLIC_ so both server and client bundles can read it
 * without leaking other env vars.
 */
export const IS_DEMO = process.env.NEXT_PUBLIC_DEMO_MODE === "true";

/**
 * Path to the runtime, writable copy of the demo DB. On Vercel only `/tmp`
 * is writable; on local dev /tmp exists on macOS and Linux. The
 * container-local nature of /tmp gives us per-cold-start isolation between
 * visitors — exactly what we want for a demo.
 */
export const DEMO_DB_RUNTIME = "/tmp/demo.db";

/**
 * Connection string that Prisma uses when IS_DEMO is true. Always points
 * at the writable runtime copy, never anything bundled.
 */
export const DEMO_DB_URL = `file:${DEMO_DB_RUNTIME}`;

let bootstrapped = false;

/**
 * Decode the base64-embedded seed DB and materialize it at /tmp/demo.db.
 * Idempotent across calls per container — the existence check short-circuits
 * once the file is on disk.
 *
 * We decode from a TypeScript constant (rather than copying from a path on
 * disk) because Vercel's Next.js file tracing doesn't reliably include
 * binary assets read with dynamic paths. The constant is generated by
 * scripts/embed-demo-db.ts during `npm run build:demo`.
 */
export function bootstrapDemoDb(): void {
  if (bootstrapped) return;
  if (!IS_DEMO) return;

  if (!DEMO_DB_BASE64) {
    throw new Error(
      "[demo] DEMO_DB_BASE64 is empty. Did the build step run " +
        "`npm run build:demo`? The stub at src/lib/demo-db-data.ts must be " +
        "overwritten by scripts/embed-demo-db.ts before next build.",
    );
  }

  const exists = fs.existsSync(DEMO_DB_RUNTIME);
  const existingSize = exists ? fs.statSync(DEMO_DB_RUNTIME).size : 0;

  if (!exists || existingSize === 0) {
    const buf = Buffer.from(DEMO_DB_BASE64, "base64");
    fs.writeFileSync(DEMO_DB_RUNTIME, buf);
    const writtenSize = fs.statSync(DEMO_DB_RUNTIME).size;
    console.log(
      `[demo] Materialized demo DB at ${DEMO_DB_RUNTIME}: ` +
        `base64=${DEMO_DB_BASE64.length} chars, ` +
        `decoded=${buf.byteLength} bytes, ` +
        `on-disk=${writtenSize} bytes`,
    );
  } else {
    console.log(
      `[demo] Reusing existing demo DB at ${DEMO_DB_RUNTIME} (${existingSize} bytes)`,
    );
  }

  bootstrapped = true;
}
