// AUTOGENERATED by scripts/embed-demo-db.ts. Do not edit.
// This stub is checked into git so type-checking passes for non-demo builds.
// `npm run build:demo` overwrites this file with the actual base64 payload.

export const DEMO_DB_BASE64 = "";
