/**
 * Derive prisma/schema.gen.prisma from prisma/schema.prisma for the public
 * demo build.
 *
 * The local app uses SQLite (a real, personally-owned file the developer keeps
 * untouched). The public demo on Vercel uses Postgres so writes survive
 * across serverless invocations. The two only differ in the `datasource db`
 * block — every model and field is portable across providers.
 *
 * Rather than committing two near-identical schemas (and forgetting to keep
 * them in sync), we generate the Postgres variant on the fly during
 * `npm run build:demo`. The generated file is git-ignored.
 *
 * Vercel Postgres auto-injects POSTGRES_PRISMA_URL (pooled, for queries) and
 * POSTGRES_URL_NON_POOLING (direct, for schema pushes / migrations), so we
 * wire both via `url` and `directUrl`.
 */
import * as fs from "node:fs";
import * as path from "node:path";

const SRC = path.resolve(__dirname, "..", "prisma", "schema.prisma");
const DEST = path.resolve(__dirname, "..", "prisma", "schema.gen.prisma");

const PG_DATASOURCE = `datasource db {
  provider  = "postgresql"
  url       = env("POSTGRES_PRISMA_URL")
  directUrl = env("POSTGRES_URL_NON_POOLING")
}`;

const SQLITE_BLOCK_RE = /datasource db \{[^}]*\}/m;

function main() {
  const source = fs.readFileSync(SRC, "utf8");
  if (!SQLITE_BLOCK_RE.test(source)) {
    throw new Error(
      `[build-demo-schema] Could not find a datasource block in ${SRC}.`,
    );
  }

  const header =
    "// AUTOGENERATED by scripts/build-demo-schema.ts. Do not edit.\n" +
    "// Source of truth is prisma/schema.prisma; this file swaps the\n" +
    "// datasource block to Postgres for the Vercel demo build.\n\n";

  const swapped = source.replace(SQLITE_BLOCK_RE, PG_DATASOURCE);
  fs.writeFileSync(DEST, header + swapped);

  // Sanity: the postgres URL env vars exist at build time on Vercel only if
  // the user actually attached a Vercel Postgres / Neon database to the
  // project. Fail loudly with a clear hint rather than letting prisma db push
  // produce a cryptic connection error 40 lines deeper into the build log.
  if (process.env.VERCEL === "1") {
    const pooled = process.env.POSTGRES_PRISMA_URL;
    const direct = process.env.POSTGRES_URL_NON_POOLING;
    if (!pooled || !direct) {
      throw new Error(
        "[build-demo-schema] Running on Vercel but POSTGRES_PRISMA_URL " +
          "and/or POSTGRES_URL_NON_POOLING are missing. Create a Postgres " +
          "database under Vercel Storage and connect it to this project " +
          "(Project Settings -> Storage -> Connect), then redeploy.",
      );
    }
  }

  console.log(
    `[build-demo-schema] Wrote ${DEST} (provider=postgresql, ` +
      `url=POSTGRES_PRISMA_URL, directUrl=POSTGRES_URL_NON_POOLING)`,
  );
}

main();
