/**
 * Derive prisma/schema.gen.prisma from prisma/schema.prisma for the public
 * demo build.
 *
 * The local app uses SQLite (a real, personally-owned file the developer keeps
 * untouched). The public demo on Vercel uses Postgres so writes survive
 * across serverless invocations. The two only differ in the `datasource db`
 * block — every model and field is portable across providers.
 *
 * Rather than committing two near-identical schemas (and forgetting to keep
 * them in sync), we generate the Postgres variant on the fly during
 * `npm run build:demo`. The generated file is git-ignored.
 *
 * Marketplace integrations inject different env-var names:
 *   - Legacy Vercel Postgres: POSTGRES_PRISMA_URL + POSTGRES_URL_NON_POOLING
 *   - Neon (via Vercel Storage): often DATABASE_URL + POSTGRES_URL_NON_POOLING
 *     or DATABASE_URL + DIRECT_URL
 * We detect whichever pair is present and wire the generated schema accordingly.
 */
import * as fs from "node:fs";
import * as path from "node:path";

const SRC = path.resolve(__dirname, "..", "prisma", "schema.prisma");
const DEST = path.resolve(__dirname, "..", "prisma", "schema.gen.prisma");

const SQLITE_BLOCK_RE = /datasource db \{[^}]*\}/m;

type PgEnv = { urlVar: string; directUrlVar: string };

/** Pick the first env-var pair that has both values set. */
function resolvePgEnv(): PgEnv | null {
  const candidates: PgEnv[] = [
    { urlVar: "POSTGRES_PRISMA_URL", directUrlVar: "POSTGRES_URL_NON_POOLING" },
    { urlVar: "DATABASE_URL", directUrlVar: "DATABASE_URL_UNPOOLED" },
    { urlVar: "DATABASE_URL", directUrlVar: "DIRECT_URL" },
    { urlVar: "DATABASE_URL", directUrlVar: "POSTGRES_URL_NON_POOLING" },
    { urlVar: "POSTGRES_PRISMA_URL", directUrlVar: "DATABASE_URL_UNPOOLED" },
  ];

  for (const c of candidates) {
    if (process.env[c.urlVar] && process.env[c.directUrlVar]) {
      return c;
    }
  }

  // Neon sometimes injects only DATABASE_URL (pooled). Prisma db push needs a
  // direct connection, but if that's all we have, use it for both and let
  // prisma fail with a connection error rather than our guard here.
  if (process.env.DATABASE_URL) {
    return { urlVar: "DATABASE_URL", directUrlVar: "DATABASE_URL" };
  }

  return null;
}

function pgDatasource({ urlVar, directUrlVar }: PgEnv): string {
  return `datasource db {
  provider  = "postgresql"
  url       = env("${urlVar}")
  directUrl = env("${directUrlVar}")
}`;
}

function main() {
  const source = fs.readFileSync(SRC, "utf8");
  if (!SQLITE_BLOCK_RE.test(source)) {
    throw new Error(
      `[build-demo-schema] Could not find a datasource block in ${SRC}.`,
    );
  }

  const pgEnv = resolvePgEnv();

  if (process.env.VERCEL === "1" && !pgEnv) {
    throw new Error(
      "[build-demo-schema] Running on Vercel but no Postgres connection " +
        "string was found. Under Storage, create a **Neon** database, " +
        "connect it to churning-treasury, then redeploy. Vercel should " +
        "auto-inject DATABASE_URL (and usually POSTGRES_URL_NON_POOLING " +
        "or DIRECT_URL).",
    );
  }

  // Local/offline demo-schema generation (no DB attached) — emit a stub that
  // type-checks; prisma generate still works, db push will fail until vars exist.
  const env =
    pgEnv ?? { urlVar: "DATABASE_URL", directUrlVar: "DIRECT_URL" };

  const header =
    "// AUTOGENERATED by scripts/build-demo-schema.ts. Do not edit.\n" +
    "// Source of truth is prisma/schema.prisma; this file swaps the\n" +
    "// datasource block to Postgres for the Vercel demo build.\n\n";

  const swapped = source.replace(SQLITE_BLOCK_RE, pgDatasource(env));
  fs.writeFileSync(DEST, header + swapped);

  console.log(
    `[build-demo-schema] Wrote ${DEST} (provider=postgresql, ` +
      `url=${env.urlVar}, directUrl=${env.directUrlVar})`,
  );
}

main();
