/**
 * Read the seeded SQLite database at prisma/demo.db and emit it as a
 * base64-encoded TypeScript module at src/lib/demo-db-data.ts. The runtime
 * (src/lib/demo.ts) then decodes that string back into /tmp/demo.db on the
 * first request per serverless container.
 *
 * Why this exists: Vercel's Next.js function bundling traces JS imports, but
 * dynamic file reads (fs.copyFileSync of a path computed at runtime) are
 * invisible to the tracer. outputFileTracingIncludes is supposed to bridge
 * that gap, but its glob matching is brittle (notably: `/**\/*` doesn't
 * match `/`). Embedding the DB as source code makes bundling completely
 * deterministic — if it compiles, it ships.
 *
 * Trade-off: the function bundle is ~190 KB larger. For a 140 KB demo DB
 * that's the right call.
 */

import * as fs from "node:fs";
import * as path from "node:path";

const SRC = path.resolve(process.cwd(), "prisma/demo.db");
const DEST = path.resolve(process.cwd(), "src/lib/demo-db-data.ts");

if (!fs.existsSync(SRC)) {
  console.error(`[embed-demo-db] Expected ${SRC} to exist. Run seed first.`);
  process.exit(1);
}

const buf = fs.readFileSync(SRC);
const b64 = buf.toString("base64");

const out =
  `// AUTOGENERATED by scripts/embed-demo-db.ts. Do not edit.\n` +
  `// Regenerated by \`npm run build:demo\`.\n` +
  `// Source file: prisma/demo.db (${buf.byteLength} bytes)\n\n` +
  `export const DEMO_DB_BASE64 = ${JSON.stringify(b64)};\n`;

fs.writeFileSync(DEST, out);
console.log(
  `[embed-demo-db] Embedded ${buf.byteLength} bytes (${b64.length} b64 chars) -> ${DEST}`,
);
